name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}] # Atualiza a cada 6 horas
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_stars: yes
          plugin_repositories: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_traffic: yes
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_projects: yes
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_limit: 5
